services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
       - .:/alerty
    env_file:
      - /alerty/.env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
      sh -c "python manage.py bot"

    depends_on:
      - database

  database:
    image: postgres:14-alpine3.17
    env_file:
      - /alerty/.env
