# Generated by Django 4.2.1 on 2023-05-18 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_bot", models.BooleanField()),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(default="", max_length=64)),
                ("username", models.CharField(default="", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language_code",
                    models.CharField(
                        choices=[("ru", "Russian"), ("en", "English")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("update_city", "update_city"),
                            ("create_reminder", "create_reminder"),
                            ("add_datetime", "add_datetime"),
                            ("update_datetime", "update_datetime"),
                            ("update_text", "update_text"),
                        ],
                        default="",
                        max_length=15,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="api.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("datetime", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("inactive", "inactive"),
                            ("done", "done"),
                            ("deleted", "deleted"),
                            ("expired", "expired"),
                            ("redacting", "redacting"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders",
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
