# Generated by Django 4.2.1 on 2023-05-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(default='', max_length=64)),
                ('username', models.CharField(default='', max_length=32)),
                ('lang_code', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('step', models.CharField(choices=[('enter_reminder', 'enter_reminder'), ('change_text', 'change_text'), ('change_datetime', 'change_datetime'), ('add_datetime', 'add_datetime'), ('change_city', 'change_city')], max_length=15)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.city')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('inactive', 'inactive'), ('done', 'done'), ('deleted', 'deleted'), ('expired', 'expired'), ('redacting', 'redacting')], max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='api.user')),
            ],
        ),
    ]
