# Generated by Django 4.2.1 on 2023-05-13 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_lang_code_user_language_code_user_is_bot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("inactive", "inactive"),
                    ("done", "done"),
                    ("deleted", "deleted"),
                    ("expired", "expired"),
                    ("redacting", "redacting"),
                ],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="api.city",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="step",
            field=models.CharField(
                choices=[
                    ("update_city", "update_city"),
                    ("create_reminder", "create_reminder"),
                    ("add_datetime", "add_datetime"),
                    ("update_datetime", "update_datetime"),
                    ("update_text", "update_text"),
                ],
                max_length=15,
            ),
        ),
    ]
