# Generated by Django 4.2.1 on 2023-05-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
